### ISSUE TITLE
Install on VSCode with PlatformIO

### ISSUE THREAD

**Issue by wgaylord** [jonask1337/esp-lwip#4]
Any suggestion how to install this modification on VSCode with PlatformIO when using the esp-idf project type. 

I tried just the normal way described and enabled "Enable copy between Layer2 and Layer3 packets". But I can't seem to actually get it to work.  Using the example code at https://github.com/jonask1337/esp-idf-nat-example

**Comment by jonask1337** [comment]
Sorry that it took so long to respond but maybe this will also help others...
I created a PlatformIO project that can be imported in VSCode (with PlatformIO). 

The code and a setup description can be found here:  https://github.com/jonask1337/esp-idf-nat-example-pio

The *"Enable copy between Layer2 and Layer3 packets"* option is already set in the *src/sdkconfig.h*.

**Comment by wgaylord** [comment]
Thanks! No problem with the long time to a response everyone has there own life to deal with. :)
