### ISSUE TITLE
How to import it on esp-idf 4.x build system ?

### ISSUE THREAD

**Issue by advaitraut** [jonask1337/esp-lwip#5]
How to import it on esp-idf 4.x build system ?
Can you give some steps for it ?

**Comment by jonask1337** [comment]
Hi, it looks like esp-idf 4.x is using a newer version of the lwip library (2.1.2). Due to this I do not think it is possible to build it with this lwip version.

**Comment by proDev-Theron** [comment]
Can't use my ESP32 as a Wifi-Repeater (a.k.a. [correct]NAT as per martin-ger)[https://github.com/martin-ger/esp_wifi_repeater]but on ESP8266 (correct me if I'm wrong, but nothing from that work for my ESP32 maybe because it's written for ESP8266). Is this the right place to start?

**Comment by proDev-Theron** [comment]
I hope someday we can do something like this: https://www.instructables.com/id/Cheap-WiFi-Range-Extender-for-IoT/

I just don't know yet how to build this one and download to ESP32.

**Comment by martin-ger** [comment]
Did that patched for lwip 2.1.2 here: https://github.com/martin-ger/esp-lwip

**Comment by advaitraut** [comment]
Thanks @martin-ger after applying the patch, its working.
Great project.
